package com.hopeandsparks.agent.enums;

public enum AgentErrorCode {
    AGENT_INPUT_INVALID,
    AGENT_MEMORY_LOAD_FAILED,
    AGENT_RETRIEVAL_FAILED,
    AGENT_SPECIALIST_FAILED,
    AGENT_DIAGRAM_RENDER_FAILED,
    AGENT_REVIEW_FAILED,
    AGENT_CHECKPOINT_FAILED,
    AGENT_RESUME_CONFLICT
}
